language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version
  - docker build -t simple-node .
  - docker tag simple-node $DOCKER_HUB/simple-node:latest

after_success:
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_HUB/simple-node
